-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
  sm:subscribe({ signal = "on_first_update", fun = this.on_first_update })
  sm:subscribe({signal = "on_inventory_open", fun = this.dof_enable})
  sm:subscribe({signal = "on_inventory_hide", fun = this.dof_disable})
  sm:subscribe({ signal = "on_talk_open",  fun = this.dof_enable    })
  sm:subscribe({ signal = "on_talk_hide",  fun = this.dof_disable })
  sm:subscribe({ signal = "on_trade_open", fun = this.dof_enable    })
  sm:subscribe({ signal = "on_trade_hide", fun = this.on_trade_hide })
  sm:subscribe({ signal = "on_body_open", fun = this.dof_enable    })
  sm:subscribe({ signal = "on_body_hide", fun = this.dof_disable })
  sm:subscribe({ signal = "on_drop_before_all", fun = this.on_item_drop })
end

local enabled = false
local first_trade_hide = true

function on_item_drop()
	if enabled then
		dof_enable()
	end
end

function on_trade_hide()
	if first_trade_hide then
		first_trade_hide = false
		return
	end
	dof_disable()
end

function dof_enable()
	set_dof_params( 1.0, 1.0, 1.0, 1.1 )
	enabled = true
end

function dof_disable()
	set_dof_params( 0.0, 0.0, 0.0, 0.0 )
	enabled = false
end

function on_first_update()
	cmd("ssfx_wpn_dof_2 0.5")
	set_dof_params( 0.0, 0.0, 0.0, 0.0 )
end
