--Меню настроек геймплея. Используется скриптом ui_mm_opt_main.script

class "opt_gameplay" (CUIWindow)
function opt_gameplay:__init() super()
end

function opt_gameplay:__finalize()
end

function opt_gameplay:InitControls(x, y, xml)
	self:Init(x, y, 738, 416)
	self:SetAutoDelete(true)

	xml:InitFrame("frame", self)

	xml:InitStatic("tab_gameplay:cap_difficulty", self)

	xml:InitCheck("tab_gameplay:check_autopause", self)
	xml:InitCheck("tab_gameplay:check_tips", self)
	xml:InitCheck("tab_gameplay:check_crosshair", self)
	xml:InitCheck("tab_gameplay:check_dyn_crosshair", self)
	xml:InitCheck("tab_gameplay:check_lock_reload", self)
	xml:InitCheck("tab_gameplay:check_dist", self)
	xml:InitCheck("tab_gameplay:check_ambient", self)
	xml:InitCheck("tab_gameplay:check_build_crosshair", self)
	xml:InitCheck("tab_gameplay:check_exclusive_input", self)
	--xml:InitCheck("tab_gameplay:check_crosshair_hard", self)
	xml:InitCheck("tab_gameplay:check_aim_toggle", self)
	xml:InitCheck("tab_gameplay:check_sprint_lower_weapon", self)
	xml:InitCheck("tab_gameplay:check_sprint_hold", self)
	xml:InitCheck("tab_gameplay:check_sticky_aim", self)
	xml:InitCheck("tab_gameplay:check_switch_slot", self)
	xml:InitCheck("tab_gameplay:check_weapon_bobbing", self)

	xml:InitStatic("tab_gameplay:cap_compass", self)
	xml:InitComboBox("tab_gameplay:list_compass", self)
	xml:InitStatic("tab_gameplay:cap_compass_pos", self)
	xml:InitComboBox("tab_gameplay:list_compass_pos", self)
	xml:InitStatic("tab_gameplay:cap_minimap_pos", self)
	xml:InitComboBox("tab_gameplay:list_minimap_pos", self)
	xml:InitStatic("tab_gameplay:cap_compass_range", self)
	xml:InitTrackBar("tab_gameplay:track_compass_range", self)
	xml:InitStatic("tab_gameplay:cap_compass_scale", self)
	xml:InitTrackBar("tab_gameplay:track_compass_scale", self)
	xml:InitStatic("tab_gameplay:cap_compass_x", self)
	xml:InitTrackBar("tab_gameplay:track_compass_x", self)
	xml:InitStatic("tab_gameplay:cap_compass_y", self)
	xml:InitTrackBar("tab_gameplay:track_compass_y", self)
	xml:InitStatic("tab_gameplay:cap_minimap_scale", self)
	xml:InitTrackBar("tab_gameplay:track_minimap_scale", self)
	xml:InitStatic("tab_gameplay:cap_minimap_x", self)
	xml:InitTrackBar("tab_gameplay:track_minimap_x", self)
	xml:InitStatic("tab_gameplay:cap_minimap_y", self)
	xml:InitTrackBar("tab_gameplay:track_minimap_y", self)

	xml:InitStatic("tab_gameplay:cap_font_scale_x", self)
	xml:InitTrackBar("tab_gameplay:track_font_scale_x", self)
	xml:InitStatic("tab_gameplay:cap_font_scale_y", self)
	xml:InitTrackBar("tab_gameplay:track_font_scale_y", self)

	xml:InitComboBox("tab_gameplay:list_difficulty", self)
end
